BOT_TOKEN = "APNA_CUSTOMER_BOT_TOKEN"
ADMIN_BOT_TOKEN = "APNA_ADMIN_BOT_TOKEN"

ADMIN_ID = 8469175911

CHANNEL_URL = "https://t.me/primesupport_boi"
CHANNEL_USERNAME = "@Premium_Mods_Reseller"

UPI_ID = "7425974582@ibl"

QR_IMAGE = "qr.jpg"
